---
- hosts: all

  roles:

    - environment-core
    - environment-nodejs
    - environment-react
    - environment-docker
    - .

  post_tasks:

    - name: Copy upstart script for docker services
      copy: src=docker-services.conf dest=/etc/init/ mode=0644
      become: yes

    - name: Start docker-services
      service: name=docker-services state=started
      become: yes

    - name: Set max user watches
      lineinfile: create=yes dest=/etc/sysctl.d/60-user.conf group=root line="fs.inotify.max_user_watches = 524288" mode="0644" owner=root regexp="^fs.inotify.max_user_watches" state=present
      become: yes

    - name: Set max user instances
      lineinfile: create=yes dest=/etc/sysctl.d/60-user.conf group=root line="fs.inotify.max_user_instances = 256" mode="0644" owner=root regexp="^fs.inotify.max_user_instances" state=present
      become: yes

    - name: Load sysctl changes
      command: sysctl -p /etc/sysctl.d/60-user.conf
      become: yes
